### PR TITLE
Bump libthermalmanager_dbus_if.so soversion

### PR DESCRIPTION
**Pull request by thp**
New version is 0.2.1 (SONAME libthermalmanager_dbus_if.so.0.2.1).

This is needed due to the new symbols added in commit 03307e9.

### CODE REVIEW

**Comment by amccarthy** [comment]
LGTM

**Comment by spiiroin** [comment]
@thp: Did you try this on target device? I could not install the resulting rpms

    # rpm -U libdsme-0.63.2-0.armv7hl.rpm 
    error: Failed dependencies:
            libthermalmanager_dbus_if.so.0.2.0 is needed by (installed) lipstick-qt5-0.27.23-1.285.1.armv7hl
            libthermalmanager_dbus_if.so.0.2.0 is needed by (installed) dsme-0.70.1-1.65.1.armv7hl

**Comment by thp** [comment]
@spiiroin The things will be rebuilt in OBS based on the build-dependencies, and then the generated dependencies will fit. You should be able to test this locally by:

* Building libdsme
* Installing libdsme + devel package into your sb2 target
* Building lipstick and dsme
* Deploying all there RPMs to your device at once

This could be avoided if the SOVERSION of the library was not taking the full version into account (or in [libtool terms](https://autotools.io/libtool/version.html), we could have bumped the `age` value, as it's a backward-compatible change).

Ideally we'd switch to CMake ([example here](http://pusling.com/blog/?p=352)) or even autotools ([example here](https://www.sourceware.org/autobook/autobook/autobook_88.html#SEC88)) to abstract away some of the custom makefile magic that's currently in libdsme's source tree. I'm aware that it's fully possible to do the proper versioning "by hand" as well, but it's additional development effort and isn't as nicely maintainable as a short CMakeList.txt

Of course, switching to e.g. CMake will only benefit us later, the first step will always cause the incompatibility, as lipstick and dsme right now depend on the /exact/ version of 0.2.0. We shouldn't even consider dirtier hacks such as creating a 0.2.0 symlink pointing to the 0.2.1 version.

**Comment by spiiroin** [comment]
Since OBS rebuilds dependencies, LGTM

**Comment by spiiroin** [comment]
Commits cherry-picked to / superseded by https://github.com/nemomobile/libdsme/pull/9

**Pull request closed without merging**
